server:
  port: 8080

spring:
  datasource:
    name: testCase
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password:

mybatis:
  mapper-locations: classpath:mappingFile/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.tia.springbootserver.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql